[package]
name = "blumblr_core"
version = "0.1.0"
edition = "2021"

[dependencies]
bsky-sdk = "0.1.16"
futures = "0.3.31"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0"
ts-rs = "10.1"
