[package]
name = "tuono-app"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "tuono"
path = ".tuono/main.rs"

[dependencies]
blumblr_core = { path = "../blumblr_core" }
tuono_lib = "0.17.8"
serde = { version = "1.0.202", features = ["derive"] }
futures = "0.3.31"
dotenvy = "0.15.7"
